name: parent_control
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  uuid: ^3.0.4
  cupertino_icons: ^1.0.6
  geoflutterfire: ^3.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  firebase_auth: ^3.11.2
  firebase_messaging: ^13.1.0
  flutter_foreground_task: ^8.8.1+1
  usage_stats: ^1.2.0
  installed_apps: ^1.5.0
  permission_handler: ^10.2.0
  flutter_svg: ^2.0.10
  geolocator: ^10.0.1
  google_maps_flutter: ^2.6.1
  cached_network_image: ^3.2.3
  quickalert: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  loading_animation_widget: ^1.3.0
  flutter_screenutil: ^5.9.3


  bloc: any
  shared_preferences: any
  equatable: ^2.0.5
dependency_overrides:
      firebase_storage: ^11.2.4
      firebase_core: ^2.12.0
      cloud_firestore: ^4.7.0
      firebase_auth: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix:


flutter:

  uses-material-design: true
  assets:
    - assets/images/

